# Generated by Django 5.1.2 on 2024-12-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userCode',
        ),
    ]
